### ISSUE TITLE
bug in GPU-related argument parsing (even when not using GPU)

### ISSUE THREAD

**Issue by flass** [johnlees/PopPUNK#70]
Hi Nick & John,

I seem to have a bug when using the latest code from fba44f1:

Having run this:
```
poppunk-runner.py --easy-run --r-files 7kVibrioCholerae_genome_fasta_list --output 7kVc --threads 8 --plot-fit 5 --min-k 13 --max-k 29 --full-db --microreact --ignore-length --estimated-length 4000000
```

I get:
```
Traceback (most recent call last):
  File "/nfs/users/nfs_f/fl4/software/PopPUNK/poppunk-runner.py", line 10, in <module>
    main()
  File "/nfs/users/nfs_f/fl4/software/PopPUNK/PopPUNK/__main__.py", line 232, in main
    dbFuncs = setupDBFuncs(args, kmers, args.min_kmer_count)
TypeError: setupDBFuncs() missing 2 required positional arguments: 'use_gpu' and 'gpu_id'
```

Can you please indicate what is the latest safe commit (including the option for providing an estimated genome length, i.e. after d410a63)?

Thanks!
Florent

**Comment by johnlees** [comment]
Sorry about all the issues you are having here! Normally I would update pp-sketchlib, then a new version of PopPUNK to work with it immediate afterwards. Unfortunately I needed to move sketchlib from bioconda to conda-forge to support GPUs, and that is still awaiting approval.

The best thing to do for now would be if you checkout `v1.1.0` of sketchlib and recompile and install as you've just done. That should work with PopPUNK v2.0.1

**Comment by flass** [comment]
Hi John, 
unfortunately, I ran through a bug when trying to compile `v1.1.0` of `pp-sketchlib`
(see https://github.com/johnlees/pp-sketchlib/issues/17).
can you suggest any other stable poppunk / pp-sketchlib commit combo?
Thanks

**Comment by johnlees** [comment]
Closed in v2.0.2
